KEY_ATTR = "attr"
KEY_ID = "_id"
KEY_TAG = "tag"
KEY_NAME = "name"
KEY_TYPE = "type"
KEY_CLASS = "class"
KEY_ACTORS = "actors"
KEY_PREP = "prep"

TAG_JJ = "JJ"
TAG_NNP = "NNP"
TAG_NNPS = "NNPS"
TAG_NN = "NN"
TAG_NNS = "NNS"

TAG_VB = "VB"
TAG_VBD = "VBD"
TAG_VBG = "VBG"
TAG_VBN = "VBN"
TAG_VBP = "VBP"
TAG_VBZ = "VBZ"
